name: Common Pipeline

on:
  workflow_call:
    inputs:
      Technology:
        required: true
        type: string

jobs:
  build:
    runs-on: sample1
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Application For Java
        if: ${{ inputs.Technology == 'java' }}
        run: |
          sudo docker build -t java-spring-image:latest .
          sudo docker images

      - name: Build Application For Node.js
        if: ${{ inputs.Technology == 'python' }}
        run: |
          sudo docker build -t nodejs-pharmacy-node:latest .
          sudo docker images    

      - name: Build Application For Python
        if: ${{ inputs.Technology == 'nodejs' }}
        run: |
          sudo docker build -t python-crude-example:latest .
          sudo docker images
